### ISSUE TITLE
The wiki not have updated info, which is diffcult to follow for hands on development

### ISSUE THREAD

**Issue by HackToday** [crosbymichael/dockerui#103]
This is the fastest way to develop with the HTML, CSS, and Javascript portion of dockerui.

clone this repo to /path/to/dockerui and cd into that directory
in the Dockerfile change ADD . /app/ to VOLUME /app
build the image : docker build -t me/dockerui ./
run the container with /path/to/dockerui binded to /app
docker run -d \
    -p 9000:9000 \
    -v /path/to/dockerui:/app me/dockerui \
    -v /var/run/docker.sock:/docker.sock \
    me/dockerui \
    -e /docker.sock

The dockerfile not have /app, also the DockerFile seems not proper to this section.

**Comment by kevana** [comment]
I added some info to the wiki [here](https://github.com/crosbymichael/dockerui/wiki/Developing-DockerUI). With the new scratch build for v0.7.0+ the easiest way is to rebuild the container when you make changes. It's a messy combo of `make` and `grunt` right now, it could definitely use some TLC.

**Comment by HackToday** [comment]
thanks @kevana  

1. did we develop/debug dockerUI with such methods ?

2. also, since I am new to docker,
if we want to run dockerui like below:

./dockerui -a dist -p 0.0.0.0:9001

for this, did that require docker demon to start with tcp ways instead of unit sock ways ?

**Comment by HackToday** [comment]
BTW, 

For steps 
make build run # (re)build image and container

What is that for ? I assume we run dockerui that on every host as web server.
Did you mean run dockerui as a container ?

**Comment by HackToday** [comment]
@kevana  a little question. I tried to debug js with firebug, but I found when build that dockerui.

Firebug can not find other source files, it can only find 
-rw-rw-r-- 1 ubuntu ubuntu 111528 Apr  3 06:03 angular.js
drwxrwxr-x 7 ubuntu ubuntu   4096 Apr  3 06:03 assets
-rw-rw-r-- 1 ubuntu ubuntu   1463 Apr  3 06:03 dockerui.css
-rw-rw-r-- 1 ubuntu ubuntu  93602 Apr  3 06:03 dockerui.js
-rw-rw-r-- 1 ubuntu ubuntu   1963 Apr  3 06:03 index.html
drwxrwxr-x 2 ubuntu ubuntu   4096 Apr  3 06:03 templates


How do you debug other core function js, like container js ?

(sorry to bother you)

**Comment by kevana** [comment]
My current workflow is:
* Make a change
* `make build run`
* Verify change

> ./dockerui -a dist -p 0.0.0.0:9001

>for this, did that require docker demon to start with tcp ways instead of unit sock ways ?

You can run it like this, but the docker socket needs to be available. If you're on a linux machine you can use the default unix socket: `/var/run/docker.sock`. If you're on OS X then you'd need to expose docker's socket outside of boot2docker with something like [socat](https://github.com/sequenceiq/docker-socat).

> make build run # (re)build image and container
> What is that for ? I assume we run dockerui that on every host as web server.
>Did you mean run dockerui as a container ?

`make build run` runs the following commands (from the Makefile):
```
# compile the javascript changes to the /dist folder
grunt build
# Rebuild the docker image for dockerui
docker build --rm -t dockerui .
# Stop and remove the running dockerui container if it exists
docker stop dockerui
docker rm dockerui
# Create a new dockerui container from the image we just built
docker run -d -p $(PORT):9000 -v /var/run/docker.sock:/docker.sock --name dockerui dockerui -e /docker.sock 
```
Whether you run DockerUI in a container or locally you'll need to run `grunt build` after every change to recompile all of the individual JS files into `dist/dockerui.js` It's similar to a compiled language. You start with source files (everything under `app/`), run them through a compiler (`grunt`), and the output ends up in the output directory `dist/`

It's a pretty complicated setup right now, I'm hoping to simplify it soon.

**Comment by HackToday** [comment]
Thanks @kevana  I got it.

**Comment by kevana** [comment]
Simplified builds and updated wiki with latest in #140, please open new issues if you run into issues with it. [dev quickstart](https://github.com/crosbymichael/dockerui/wiki/Developing-DockerUI)
