### ISSUE TITLE
File not found error from Make run on debian

### ISSUE THREAD

**Issue by nissimk** [crosbymichael/dockerui#112]
Hello, I tried to run the server using "make run" on Debian and I was getting file not found errors from the docker run command.  It turns out that it was related to carriage return (\r) characters in the Dockerfile as described here: http://stackoverflow.com/questions/26842629/docker-cannot-start-container-no-such-file-or-directory.  I ran dos2unix command on Dockerfile and rebuilt and the problem is resolved.  dos2unix command replaces \r\n with \n.  Would you like me to submit a pull request for this?

Thanks.

**Comment by kevana** [comment]
Good catch, a PR would be great but I can do it if you don't have time.

**Comment by kevana** [comment]
This should be fixed, let me know if you run into more issues.
