### ISSUE TITLE
How you have connected unix socket to ip socket.

### ISSUE THREAD

**Issue by amankumarjain** [crosbymichael/dockerui#114]
Remote client make rest request to ip(ip:port) socket, how to redirect that data to unix docker socket.

**Comment by kevana** [comment]
Could you provide more info about what you're trying to do?

**Comment by amankumarjain** [comment]
A web gui for managing docker container.

**Comment by kevana** [comment]
Ah, if you're planning on making your own or starting with DockerUI as a base, look at `dockerui.go`. An HTTP mux routes all requests to routes starting with `/dockerapi` [(source)](https://github.com/crosbymichael/dockerui/blob/master/dockerui.go#L88) to the unix socket and strips the /dockerapi from the front. All other requests are served from a static file handler.

**Comment by kevana** [comment]
Closing, let me know if you have other questions.
