### ISSUE TITLE
Compose related bug

### ISSUE THREAD

**Issue by octplane** [crosbymichael/dockerui#117]
Because there is no /bin/echo in the dockerui image, it triggers https://github.com/docker/compose/issues/919 .

Just adding the bug here as a note.

**Comment by kevana** [comment]
Planning to close when docker/compose#1349 hits a release.

**Comment by psychemedia** [comment]
Any ideas how can I run dockerui with this bug outstanding?

 I am launching from vagrant using docker compose and all's well if force rebuild = true, but to persist database containers I need rebuild = false, which raises this echo error with dockerui.

**Comment by kevana** [comment]
We don't have `echo` or `true`, just the DockerUI binary in the container, but you should be able to add files to it with something like this:

```
FROM dockerui/dockerui:0.7.0
COPY /bin/echo /bin/echo
```

**Comment by psychemedia** [comment]
That didnlt actually work for  me, but adding in the `echo` executable from  https://github.com/cogniteev/docker-echo (as per https://registry.hub.docker.com/u/cogniteev/echo/dockerfile/) seemed to do the trick

**Comment by kevana** [comment]
Whoops, on OS X it's `/bin/echo`, on linux it might be somewhere else like `/usr/bin/echo` depending on the distro.
