### ISSUE TITLE
How to pull images / create container from repo image ?

### ISSUE THREAD

**Issue by janeczku** [crosbymichael/dockerui#118]
I may not to see the wood for the trees, but i cant find the option to pull a remote image, nor to run a container from a remote image.
So, how to use dockerui in order to do the equivalent of the most basic docker task: `docker run -d tutum/nginx` ?
Does dockerui only work with local images?

**Comment by kevana** [comment]
Correct, DockerUI only works with local images right now. Why? Docker's streaming JSON format, namely returning multiple top-level JSON objects, doesn't play well with libs like [OboeJS](http://oboejs.com/).

**Comment by janeczku** [comment]
I see, thanks for clearing this up as this limitation was really not obvious at all from the documentation.
Hope you find the time to add this sometime soon! :-)

**Comment by hmichopoulos** [comment]
Performed a workaround for this. I combined the top-level json objects to an array. If the last object contains an error description, pull is considered to have failed, otherwise to have succeeded. Details in the PR.

**Comment by kevana** [comment]
Sorry this took so long, merged in #125
