### ISSUE TITLE
volume json error

### ISSUE THREAD

**Issue by IMikkeI** [crosbymichael/dockerui#129]
Hi,

When I try to create a new container, I want to give the -v option. So in the "Create And Start Container From Image" window, I put "/tmp/.X11-unix:/tmp/.X11-unix:rw" in the volumes box. But I have the following error : 
```json: cannot unmarshal array into Go value of type map[string]struct {}```

Can someone give me any help ?

Thanks

Mikke

**Comment by kevana** [comment]
This still isn't very well documented, try the following:
Volumes: `/tmp/.X11-unix`
Binds: `/tmp/.X11-unix:/tmp/.X11-unix:rw`

The `-v` option on the command line hides two separate steps, declaring the volume and performing the bind to the host. With the remote API we have to do both explicitly.

Special thanks to @wrzasa for finding [this](https://github.com/docker/docker/issues/2949#issuecomment-33516489) earlier.

**Comment by IMikkeI** [comment]
Ok thank you for your help :)
