### ISSUE TITLE
Incorrect container name if container has links

### ISSUE THREAD

**Issue by mbonaci** [crosbymichael/dockerui#132]
As you can see from the attached image, the container `st-mysql` has incorrect name.
That container has incoming link from `st-flyway` container and it looks as though the alias of that link got included instead of container's name.

![dockerui-bug](https://cloud.githubusercontent.com/assets/497926/8995102/aa41f442-370f-11e5-9e2a-77372293dd94.png)

This is `Links` property from `docker inspect st-flyway`:
```
"Links": [
    "/st-mysql:/st-flyway/db"
],
```

And this is the command that was used to run `st-flyway` container (only relevant params included):

```
$ docker run --name st-flyway --link st-mysql:db -d shouldbee/flyway
```

**Comment by kevana** [comment]
Container names are taken directly from the `Names` array that comes back from the Docker API and the leading slash is removed. If you're still seeing this behavior it might be a Docker bug.
