### ISSUE TITLE
Dashboard - Containers created no data - RHEL v7.1

### ISSUE THREAD

**Issue by Mr-H** [crosbymichael/dockerui#134]
Using the docker pull dockerui/dockerui from today with Docker 1.17 UI v0.7.0 GIT Commit 3043001/1.7.1 Go Version go1.4.2 on RHEL v7.1 Kernel 3.10.0.229.el7.x86_64 

The Dashboard Containers created graph shows no data despite making a bunch of new containers. Everything else is working fine. 

Mike

**Comment by Mr-H** [comment]
I went back into it today and it is working. I am not sure why it was empty but this may be a connection or a restart problem.

**Comment by kevana** [comment]
When the daemon is busy I've noticed some considerable lag with remote API calls, might've been something like that. If it happens consistently let me know and I'll reopen, thanks.
