### ISSUE TITLE
Add website logo

### ISSUE THREAD

**Issue by nhducit** [crosbymichael/dockerui#142]
Currently website's logo is bootstrap icon

**Comment by jandanielcz** [comment]
Hi, I have made first attempt for DockerUI logo and favicon.
![dockeruiv1](https://cloud.githubusercontent.com/assets/219847/10427352/3db08780-70e9-11e5-88eb-46d7d8dba8db.png)
We can place it as favicon and before heading text:
![dockerui-logo-placement](https://cloud.githubusercontent.com/assets/219847/10427351/3db06c1e-70e9-11e5-944f-40d99706a04c.png)
I am interested in feedback :-)

Note:
Its whale tail (docker, tail for logs...) its different from official docker whale to avoid [boring legal stuff](https://www.docker.com/brand-guidelines).

**Comment by crosbymichael** [comment]
LGTM

**Comment by kevana** [comment]
@crosbymichael Are you sure? Whale tail has a connotation we might not want.

**Comment by crosbymichael** [comment]
@kevana lol

what other type of logo can we have?

**Comment by kevana** [comment]
The only thing I've come up with is maybe zoom in on the whale's eye, playing off DockerU**EYE**, but that's pretty punny. Also not sure if using parts of the existing logo is kosher.

![dockerui-logo](https://cloud.githubusercontent.com/assets/981551/10434205/da3f572c-70dd-11e5-951d-cbbb726519ac.png)

**Comment by jandanielcz** [comment]
I do not think whale tail is an issue :-) Because whales has tails... but IT maybe has to be more cautious now, when even "master / slave" is forbidden :D 

Should I try to create whale eye, similar but not same?

**Comment by ronsmits** [comment]
Maybe me but whale tail connotation? I don't see that

**Comment by jandanielcz** [comment]
@ronsmits try google images... its slang for panties visible from pants.

**Comment by linquize** [comment]
Nice idea to have logo in dockerui UI
