### ISSUE TITLE
connect() to unix:/var/run/docker.sock failed (13: Permission denied) while connecting to upstream

### ISSUE THREAD

**Issue by a1exus** [crosbymichael/dockerui#147]
I'm trying to implement [Dockerui with Nginx HTTP Auth](https://github.com/crosbymichael/dockerui/wiki/Dockerui-with-Nginx-HTTP-Auth).
I start two docker containers (dockerui and nginx):

```
root@alexus:~# docker ps --filter name=dockerui 
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
8fc6f671ec94        dockerui/dockerui   "/dockerui"         8 minutes ago       Up 8 minutes        9000/tcp            dockerui
root@alexus:~# docker ps --filter name=nginx
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                         NAMES
28ec79df973f        nginx               "nginx -g 'daemon off"   6 minutes ago       Up 6 minutes        0.0.0.0:80->80/tcp, 443/tcp   nginx
root@alexus:~# 
```

while trying to reach dockerui, I encounter following critical error (inside of dockerui.error.log):

```
2015/10/16 16:51:22 [crit] 10#10: *6 connect() to unix:/var/run/docker.sock failed (13: Permission denied) while connecting to upstream, client: Y.Y.Y.Y, server: X.X.X.X, request: "GET / HTTP/1.1", upstream: "http://unix:/var/run/docker.sock:/", host: "X.X.X.X"
2015/10/16 16:51:22 [crit] 10#10: *6 connect() to unix:/var/run/docker.sock failed (13: Permission denied) while connecting to upstream, client: Y.Y.Y.Y, server: X.X.X.X, request: "GET / HTTP/1.1", upstream: "http://unix:/var/run/docker.sock:/", host: "X.X.X.X"
```

According to error message problem is with permissions. I've tried adjusting permissions, but that did not do any good for me, as I'm still getting same error:

```
root@alexus:~# ll /var/run/docker.sock 
srw-rw---- 1 root docker 0 Oct 15 11:31 /var/run/docker.sock=
root@alexus:~# ps auxww | grep nginx
root     10700  0.0  0.5  31520  2800 ?        Ss   12:49   0:00 nginx: master process nginx -g daemon off;
sshd     10709  0.0  0.3  31896  1936 ?        S    12:49   0:00 nginx: worker process
root     10800  0.0  0.1  11740   932 pts/1    S+   12:57   0:00 grep --color=auto nginx
root@alexus:~# 
root@alexus:~# chmod o+rx /var/run/docker.sock 
root@alexus:~# ll /var/run/docker.sock 
srw-rw-r-x 1 root docker 0 Oct 15 11:31 /var/run/docker.sock=
root@alexus:~# 
```

My system:

```
root@alexus:~# cat /etc/issue.net 
Ubuntu 14.04.3 LTS
root@alexus:~# uname -a
Linux alexus 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
root@alexus:~# 
```

please advise

**Comment by kevana** [comment]
`/var/run/docker.sock` lives in the DockerUI container, I don't think you'll have access to it from the Nginx container. I think the easiest way is to link them and use a TCP port to talk to DockerUI

Warning: Incomplete and untested:
```
# docker-compose.yml
dockerui:
  image: dockerui/dockerui
nginx:
  build: ./nginx
  links:
   - dockerui
  ports:
   - 80:80
```
with an upstream of:
```
upstream dockerui {
    server dockerui:9000;
}
```

I'm pretty busy with work for the next few weeks but I'd like to get a sample repo put together with it.

**Comment by a1exus** [comment]
I use "Bind mount a volume" (`--volume=/var/run/docker.sock:/var/run/docker.sock`) while running *dockerui* container and exactly same syntax for *nginx* container as well, that gives *nginx* container same access as *dockerui* container.

**Comment by kevana** [comment]
`docker.sock` is the socket that the Docker daemon exposes the remote API on. The DockerUI container talks to the daemon via `docker.sock`, Nginx doesn't need access to it. DockerUI serves the web interface via TCP only (using [http.ListenAndServe](https://golang.org/pkg/net/http/#ListenAndServe)). You can change the port but it can't serve on a unix socket. The Nginx container needs access to that endpoint and using Docker links prevents the DockerUI endpoint from being exposed externally.

**Comment by a1exus** [comment]
I was confused by [Dockerui with Nginx HTTP Auth · crosbymichael/dockerui Wiki](https://github.com/crosbymichael/dockerui/wiki/Dockerui-with-Nginx-HTTP-Auth), as very first step describes *upstream* portion of configuration file and it refers to a socket, but your comment earlier makes total sense, I'll take out socket part and point it to IP and port instead.

Thanks!

**Comment by kevana** [comment]
No problem, that section isn't very clear, I'll try to put an example together soon.

**Comment by a1exus** [comment]
Can `--expose` be used instead of `--publish` to make it more secure?

```
root@alexus:~# docker ps --filter name=dockerui
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
8e3717926817        dockerui/dockerui   "/dockerui"         6 minutes ago       Up 6 minutes        9000/tcp            dockerui
root@alexus:~# ifconfig docker0 | grep inet
          inet addr:172.17.42.1  Bcast:0.0.0.0  Mask:255.255.0.0
root@alexus:~# curl 172.17.42.1:9000
curl: (7) Failed to connect to 172.17.42.1 port 9000: Connection refused
root@alexus:~# 
```

**Comment by kevana** [comment]
Maybe. I'm off to a football game, can check later

**Comment by a1exus** [comment]
... meanwhile, I tried to run with `--publish=127.0.0.1:9000:9000`:

```
root@alexus:~/root/etc/nginx/conf.d# docker ps --filter name=dockerui
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                      NAMES
a17a7c76695c        dockerui/dockerui   "/dockerui"         5 minutes ago       Up 5 minutes        127.0.0.1:9000->9000/tcp   dockerui
root@alexus:~/root/etc/nginx/conf.d# grep 'server.*:9000' dockerui.conf 
	server 127.0.0.1:9000;
root@alexus:~/root/etc/nginx/conf.d# curl -I 127.0.0.1:9000
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 1927
Content-Type: text/html; charset=utf-8
Last-Modified: Wed, 16 Sep 2015 03:49:16 GMT
Date: Sat, 17 Oct 2015 16:04:44 GMT

root@alexus:~/root/etc/nginx/conf.d# 
```

yet still unable to access dockerui via nginx (`502 Bad Gateway`) ...

**Comment by kevana** [comment]
Created a docker-compose example in #160

**Comment by kevana** [comment]
The [example](https://github.com/crosbymichael/dockerui/tree/master/examples/nginx-basic-auth) uses an internal docker link between Nginx and DockerUI, it isn't accessible externally. Let me know if you have any other questions
