### ISSUE TITLE
Add a refresh button and a refresh key (F5?)

### ISSUE THREAD

**Issue by vberruchon** [crosbymichael/dockerui#150]
Perhaps I've missed something but I can't see any refresh button.

It seems that one need to go to another tab and come back get information refresh...
So probably a refresh button + refresh key (F5] would help.

Thank you for this nice tool.

**Comment by kevana** [comment]
Do you think people would prefer a refresh button or updating automatically every x seconds?

**Comment by vberruchon** [comment]
Personnally, I do prefer to have to force a refresh as soon as I want and not to wait for a timer.
Having a button to click is necessary for a graphical UI, but a keyboard shortcut like the standard F5 key  is the fastest way for me.
My 2 cents ;)

**Comment by kevana** [comment]
I think I might defer to the browser's refresh button and keyboard shortcuts. Is there any situation where this doesn't work?

**Comment by linquize** [comment]
User may not aware that dockerui is a single page application. Pressing F5 does not do the job.

**Comment by taiidani** [comment]
I for one just stumbled upon this project. The single-page app feel doesn't come across very well for first impressions -- I kept wanting to refresh with F5 and each time got the landing page jumbotron message. It was pretty jarring.

**Comment by kevana** [comment]
@taiidani It'd be great if you could provide some feedback on #166 too.

**Comment by kevana** [comment]
I added a refresh button in the latest `0.9.0-beta` image on the hub, let me know what you think.
