### ISSUE TITLE
Restart policy does not show in the "Create And Start Container From Image" dialog.

### ISSUE THREAD

**Issue by Zone22** [crosbymichael/dockerui#152]
Restart policy does not show in the "Create And Start Container From Image" dialog.
Edited: The absence of the Restart policy that should already be implemented.

**Comment by mausch** [comment]
AFAIK Docker does not allow changing the restart policy of an existing container. You'd have to start a new one. In which case it would be nice if dockerui had the restart policy option included in the "Create And Start Container From Image" dialog.

**Comment by kevana** [comment]
Restart policy should be implemented already, see [here](https://github.com/crosbymichael/dockerui/blob/master/app/components/startContainer/startcontainer.html#L292-L302)

**Comment by mausch** [comment]
@kevana Thanks! However for some reason I don't see it in the actual UI or in the [controller](https://github.com/crosbymichael/dockerui/blob/master/app/components/startContainer/startContainerController.js)...  (running 0.8.0 beta)

![](http://i.imgur.com/LuX4Bdo.png)

**Comment by kevana** [comment]
That's odd...

**Comment by kevana** [comment]
Fix should be in the latest `0.8.0-beta` image on the hub if you'd like to verify.
