### ISSUE TITLE
500 Internal Server Error: /dockerapi/containers/json?all=1

### ISSUE THREAD

**Issue by AndyQu** [crosbymichael/dockerui#156]
I run my docker daemon in a ubuntu server, over a tcp socket: 

    alias dock='docker -H tcp://localhost:4243'

Then I run dockerui

    dock run -d -p 9000:9000 --privileged dockerui/dockerui -e tcp://127.0.0.1:4243

This way the container will exit. So I change "tcp" to "http"

    dock run -d -p 9000:9000 --privileged dockerui/dockerui -e http://127.0.0.1:4243

dockerui runs up successfully. However, when I run

    curl -v http://172.27.2.94:9000/dockerapi/containers/json?all=1
    //172.27.2.94 is my server ip

500 Internal Server Error occurs.

    andydeMacBook-Pro:Common andy$ curl -v http://172.27.2.94:9000/dockerapi/containers/json?all=1
    *   Trying 172.27.2.94...
    * Connected to 172.27.2.94 (172.27.2.94) port 9000 (#0)
    > GET /dockerapi/containers/json?all=1 HTTP/1.1
    > Host: 172.27.2.94:9000
    > User-Agent: curl/7.43.0
    > Accept: */*
    > 
    < HTTP/1.1 500 Internal Server Error
    < Date: Wed, 02 Dec 2015 03:53:49 GMT
    < Content-Length: 0
    < Content-Type: text/plain; charset=utf-8
    < 
    * Connection #0 to host 172.27.2.94 left intact

Are there logs for dockerui so that I can check them?

**Comment by kevana** [comment]
the logs from the dockerui container should have any output: `docker logs container_name`

**Comment by AndyQu** [comment]
the logs show:
    
    2015/12/02 04:57:38 http: proxy error: dial tcp 127.0.0.1:4243: connection refused

but my docker can connect to 127.0.0.1:4243

**Comment by kevana** [comment]
127.0.0.1 is referencing the dockerui container's localhost, not the docker host's localhost. I think you'd need to bind port 4243 in the container as well:

```
dock run -d -p 9000:9000 -p 4243:4243 --privileged dockerui/dockerui -e http://127.0.0.1:4243
```

**Comment by AndyQu** [comment]
Thank you very much. I changed the ip.

    dock run -d -p 9000:9000 dockerui/dockerui -e http://172.27.2.94:4243

Then it worked~
