### ISSUE TITLE
Use DockerUI as private registry frontend?

### ISSUE THREAD

**Issue by maxa4e** [crosbymichael/dockerui#161]
The containers are visible 
but would it be good enough to use as private registry frontend in production atm?

**Comment by kevana** [comment]
DockerUI talks to a single Docker daemon, it doesn't have any registry frontend features. The most popular registry frontend that I know of is https://github.com/kwk/docker-registry-frontend

**Comment by kevana** [comment]
If you're just looking for a display of the repos and images on a registry, check out [kevana/docker-registry-2.0-ui](https://github.com/kevana/docker-registry-2.0-ui). It's readonly, but that's all we've needed so far with our registry.
