### ISSUE TITLE
Stats AJAX failures

### ISSUE THREAD

**Issue by virtualfunction** [crosbymichael/dockerui#173]
I've noticed the stats occasionally don't update and I get a "failure to get stats" error. After which the stats stop updating.It would be good if it can at least try and resume again afterwards at the next cycle.

Looking at the logs it seems there's a 2s timeout for the AJAX query which is causing this.

This is using 0.9.x beta and Docker 1.9.1

**Comment by andreas4all** [comment]
+1

**Comment by linquize** [comment]
2s timeout too short?

**Comment by virtualfunction** [comment]
A lot of requests are in the 1.7-1.9s mark so 2s is too short... more importantly if call fails, it needs to be able to resume where it left off on the next cycle rather than stop the graphs indefinitely

**Comment by kevana** [comment]
Bumped the timeout and interval to 5s, and it now keeps retrying if a request fails. On the hub, new build of `0.9.0-beta`

**Comment by virtualfunction** [comment]
Thanks for doing this so quickly :)
