### ISSUE TITLE
DockerUI auth

### ISSUE THREAD

**Issue by whitechapplin** [crosbymichael/dockerui#175]
Hello,

i found this entrence in the Wiki:
https://github.com/crosbymichael/dockerui/wiki/Dockerui-with-Nginx-HTTP-Auth

I need to add the Basic Auth, but i have now Idea where and how I can add the file. Please help me to set basic auth up. Do i need Docker-Compose for it?

**Comment by kevana** [comment]
I put an example together recently: https://github.com/crosbymichael/dockerui/tree/master/examples/nginx-basic-auth

**Comment by whitechapplin** [comment]
Hey, thank you for your quick reply.

I have still no idea how to manage the Problem. Must I install nginx on the System, or must I create a new Container. And do I need Docker-Compose?

**Comment by kevana** [comment]
The example uses docker-compose to start 2 containers (DockerUI and Nginx) and link them. The Nginx container exposes ports to the world and all communication with DockerUI goes through it.

**Comment by virtualfunction** [comment]
@whitechapplin - Yes, you'll need docker compose. If you use Debian / Ubuntu you can `sudo apt-get install docker-compose` if you installed Docker from the install script on the Docker website (as opposed to the old dated docker.io package in the distro repo). You should be able to do `sudo docker-compose up` from the example git repo to get things running (you need to use sudo as nginx binds to port 80 which needs root access). `docker-compose up` will grab the container images in the same way docker run will pull them if they aren't there locally.

**Comment by kevana** [comment]
Let us know if you have any other questions
