### ISSUE TITLE
Commit on a stopped container

### ISSUE THREAD

**Issue by WTFKr0** [crosbymichael/dockerui#176]
Hi,

Is it possible to add the commit button on a stopped container ?
The docker api allow that.

Thanx

**Comment by kevana** [comment]
Yep, definitely possible, it's in container.html if you'd like to submit a PR.

**Comment by kevana** [comment]
Fixed in 786b94b285119600905acc568f144eb57d19fee6, `0.10.0-beta` on the hub.
