### ISSUE TITLE
Restrict the login

### ISSUE THREAD

**Issue by openspacetech** [crosbymichael/dockerui#181]
Dear 

I must say that i love dockerui. 

I want to know if there is a way for me to restrict it from people to just get into it. If there is a possibility to add LOGIN screen -- which can be docker host machine login. 

Let me know if thats possible. 

Regards
Manish

**Comment by kevana** [comment]
My recommendation is to use your favorite reverse proxy (I prefer Nginx) for auth, there's an example docker-compose setup with basic auth [here](https://github.com/crosbymichael/dockerui/tree/master/examples/nginx-basic-auth). Auth in DockerUI itself is out of scope and we won't be adding it.

**Comment by openspacetech** [comment]
Thank you. This great. 

Manish
