### ISSUE TITLE
Check all Action also checks unfiltered list items

### ISSUE THREAD

**Issue by pmig** [crosbymichael/dockerui#194]
How to reproduce:

1. Filter some list items
2. Check all
3. remove the filter

=> now all List items are filtered

This behavior is very toxic. I just wanted to remove some filtered images and ended up remove all images. This shouldn't have happened.

**Comment by kevana** [comment]
I'll take a look at this as soon as I can, sorry!

**Comment by pmig** [comment]
don't worry, do you accept pull requests on this issue?

**Comment by kevana** [comment]
Of course, PRs are always welcome

**Comment by pmig** [comment]
Ok,

I'll give it a try tomorrow and report either way in the next couple of
days!

Really helpful and slim ui btw!

Thanks.

On 24 March 2016 at 19:07, Kevan Ahlquist <notifications@github.com> wrote:

> Of course, PRs are always welcome
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/crosbymichael/dockerui/issues/194#issuecomment-200953138>
>



-- 
Philip Miglinci
pmig.at

Contact:
+43 660 5531000
Skype: MainstreamOP
p.miglinci@gmail.com
Facebook <https://www.facebook.com/philip.miglinci>, Twitter
<https://twitter.com/pmigat>, G+
<https://plus.google.com/117112292948923852689>, Github
<https://github.com/pmig>, Xing
<https://www.xing.com/profile/Philip_Miglinci>, LinkedIn
<https://www.linkedin.com/profile/view?id=188196578>
