### ISSUE TITLE
The link of image is wrong

### ISSUE THREAD

**Issue by tobegit3hub** [crosbymichael/dockerui#56]
In the containers page, the name of the container may be id or identifiable string. If it's id, we can click and redirect to the image page correctly. But if it's the name like "crosbymichael/dockerui:latest", I click and go to the home page unexpectedly.

Maybe we should not add <a> in the name of containers because the docker remote API may return both id or string.

**Comment by sdejean28** [comment]
i think this is because image name contains a '/' ....
for image name without it works !
