### ISSUE TITLE
Documentation error or bug on centos 7

### ISSUE THREAD

**Issue by salboaie** [crosbymichael/dockerui#62]
I try to start dockerui with command from documentation on centos 7

docker run -d -p 9000:9000 -v /var/run/docker.sock:/docker.sock crosbymichael/dockerui -e /docker.sock

The problem is, this command just exits, no server listen on 9000 and "docker ps" don't show a container running.
Do I understand something wrong, I'm new with docker but I succeed running shipyard for example.
Any help please?
Thank you

**Comment by kevana** [comment]
The docs have been updated and we have an official repo at `dockerui/dockerui` now.
