### ISSUE TITLE
Ability to specify "DOCKER_ENDPOINT"

### ISSUE THREAD

**Issue by TheBlusky** [crosbymichael/dockerui#73]
(I'm new to Docker, so maybe I'm doing this thing the wrond way)
(This is not actually an issue, but more a enhancement suggestion)

My docker host doesn't have multiple hostname, so for every container service, I have a reverse proxy with this syntax :
http://[docker Host]/[docker container] ----> http://[docker container].

dockerui works fine with this configuration, except that ajax call are made to
http://[docker Host]/dockerapi/containers/json?all=1
instead of
http://[docker Host]/[docker container]/dockerapi/containers/json?all=1

(Because of the "/" in .constant('DOCKER_ENDPOINT', '/dockerapi'))

Quick work around (in order to change the DOCKER_ENDPOINT value:
docker exec [docker container] sed "s/dockerapi/[docker container]\/dockerapi/" app/app.js

It's working fine now, but it's not a beautiful method :-)

It would be nice to be able to put a DOCKER_ENDPOINT prefixe, or to remove the "/" in '/dockerui/dockerapi'.

**Comment by kevana** [comment]
I think removing the leading `/` will do the trick:

    .constant('DOCKER_ENDPOINT', 'dockerapi')

Care to submit a PR?

**Comment by kevana** [comment]
The change I mentioned is merged and on the registry, let us know if you still run into issues with it.
