### ISSUE TITLE
The configuration for administrative operations

### ISSUE THREAD

**Issue by Powpow-Shen** [crosbymichael/dockerui#74]
Thank you for creating this web ui for docker management.
Can we also have an configuration for administrative operations? If we can configure that, then it will be fine to open this ui to some users on production. Especially the "kill" and "remove" button should be hidden for some users.

**Comment by davivcgarcia** [comment]
@Powpow-Shen As far as I understand, the way the DockerUI is designed today this capability is not possible. I think there are plans to change it in order to implement accounts/permission, but not in short term.

**Comment by Powpow-Shen** [comment]
@davivcgarcia I understood. The effort would be big for now. I think we can close this issue for now. Thank you for the quick reply.
