### ISSUE TITLE
Container stdout/stderr: "Display Timestamps" does not stamp stderr

### ISSUE THREAD

**Issue by sirkkalap** [crosbymichael/dockerui#80]
Hi. For Me the `Display Timestamps` only decorates the stdout. I have `Docker API Version: v1.16 UI Version: v0.6.0`.

![screenshot 2015-02-09 20 17 57](https://cloud.githubusercontent.com/assets/703699/6112456/d1746142-b098-11e4-8e21-c64abf97a077.png)

**Comment by kevana** [comment]
I must've missed stderr when I built it, I'll take a look.
