### ISSUE TITLE
Port mappings are not visible

### ISSUE THREAD

**Issue by dasJ** [crosbymichael/dockerui#83]
When viewing a container, the port mappings are not visible (tried in Chrome, Firefox, and IE). Screenshot:
![image](https://cloud.githubusercontent.com/assets/4971975/6165459/65628b48-b2a8-11e4-8780-e6fe41d18d05.png)

The text is there, but it's color is white (visible when selecting):
![image](https://cloud.githubusercontent.com/assets/4971975/6165470/854c3062-b2a8-11e4-9bfb-3c4daaa23e16.png)

**Comment by sdejean28** [comment]
we should change container.html line 63, change from
class="label"
to
class="label label-default"
