### ISSUE TITLE
Add filter option for containers and images

### ISSUE THREAD

**Issue by dasJ** [crosbymichael/dockerui#84]
When having a huge amount of containers, it would be awesome to filter them with a native feature. 
Example: I have containers for my product, which are called "*db-productA*", and "*app-productA*".
When searching for *productA*, I'd have all containers together (which is not possible when using the browser's feature Ctrl+F).

**Comment by sdejean28** [comment]
i think we could add a filter box in containers.html

    <div class="pull-right">
        <div class="form-group">
			<label class="sr-only" for="filter">Filter</label>
			<input type="text" class="form-control" id="filter" placeholder="Filter" ng-model="filter">
		  </div>
    </div>

and change the update() in containersController.js to chain a filter after map (or before ?) :

$scope.filter = '';

    var update = function(data) {
        ViewSpinner.spin();
        Container.query(data, function(d) {
            $scope.containers = d.map(function(item) {
                return new ContainerViewModel(item); }).filter(function(item) {
                return ($scope.filter.length==0)||(item.Names[0].toLowerCase().indexOf($scope.filter.toLowerCase())>=0); });
            ViewSpinner.stop();
        });
    };

a watch to filter would also be necessary ;
	$scope.$watch('filter', function() {
	   $scope.update();
   } , true);

**Comment by tehbilly** [comment]
Should be even simpler than that, no need to add a watch or use update/apply.

```html
<tr ng-repeat="image in images | orderBy:predicate">
```

becomes

```html
<tr ng-repeat="image in images | filter:filterModel | orderBy:predicate">
```

**Comment by zhucegep** [comment]
@sdejean28 It works,thank you.
