### ISSUE TITLE
Image name is not loaded when opening from containers page

### ISSUE THREAD

**Issue by dasJ** [crosbymichael/dockerui#87]
When I'm viewing a container and click the image hash, the name at the top of the page is not loaded.

![image](https://cloud.githubusercontent.com/assets/4971975/6185196/e89569c2-b36b-11e4-9e6a-2bd3cb22fd1f.png)

**Comment by davivcgarcia** [comment]
@dasJ Which branch/tag are you using? Have you tested with latest code version?

**Comment by budhrg** [comment]
I am also able to reproduce the latest build(commit `964eac6d530a7600459f92c312d79ee9365b0f9b`).
