### ISSUE TITLE
Add commit button to docker containers

### ISSUE THREAD

**Issue by dasJ** [crosbymichael/dockerui#88]
It would be great to have commit button (next to the Pause/Unpause button). Could look like this:
![image](https://cloud.githubusercontent.com/assets/4971975/6185637/24cc07fc-b371-11e4-9dc2-e57abb1d5adb.png)
Green was just a nice looking color, but I would take another, because the Unpause button already has this color.

**Comment by bharaththiruveedula** [comment]
Can I work on this issue?

**Comment by kevana** [comment]
Go for it. I don't think anyone is working on it now.

**Comment by bharaththiruveedula** [comment]
@kevana, thanks, I will work on this!

**Comment by bharaththiruveedula** [comment]
@kevana @crosbymichael , Created PR https://github.com/crosbymichael/dockerui/pull/116, can you please review?

**Comment by kevana** [comment]
Merged, thanks.
