### ISSUE TITLE
Minimize commit changes by ignoring dist directory

### ISSUE THREAD

**Issue by dasJ** [crosbymichael/dockerui#93]
As it looks to me, the contents of the dist directory get generated from the app directory. So there is no need to check the dist directory into Git, or am I wrong here?

**Comment by kevana** [comment]
We need to check the dist directory in for the automated image build on the registry. It's not ideal, but I haven't come up with a way to get around that. Maybe if we only checked it in right before releases?

**Comment by dasJ** [comment]
Or using another branch?

**Comment by kevana** [comment]
I'll make a `dist` branch. If you know how to do per-branch excludes without worrying about clobbering the .gitignore every merge let me know, [this solution](http://stackoverflow.com/questions/1836742/using-git-how-do-i-ignore-a-file-in-one-branch-but-have-it-committed-in-another) doesn't seem to work anymore.

**Comment by kevana** [comment]
Fixed by #85.
