### ISSUE TITLE
Incorrect first character on each log line

### ISSUE THREAD

**Issue by marcv81** [crosbymichael/dockerui#94]
The first character of each log line is incorrect. It may or may not be a printable character.

===

DockerUI log:
AFeb 18, 2015 11:52:49 PM org.apache.coyote.AbstractProtocol init
5INFO: Initializing ProtocolHandler ["http-bio-8080"]
CFeb 18, 2015 11:52:49 PM org.apache.catalina.startup.Catalina load
)INFO: Initialization processed in 887 ms
PFeb 18, 2015 11:52:49 PM org.apache.catalina.core.StandardService startInternal
 INFO: Starting service Catalina
...

Result of "docker logs <container_id>":
Feb 18, 2015 11:52:49 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8080"]
Feb 18, 2015 11:52:49 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 887 ms
Feb 18, 2015 11:52:49 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
...

**Comment by kevana** [comment]
Looks like the logs endpoint uses the same 8-byte header that attach does ([docs](https://docs.docker.com/reference/api/docker_remote_api_v1.17/#attach-to-a-container)). For DockerUI I think we'd be safe stripping the first 8 bytes of every line before display.
